name: Typecheck
on:
  push:
    branches: [ "**" ]
    tags: [ "*" ]
  pull_request:

permissions:
  contents: read

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
      - uses: go-task/setup-task@v1
      - run: task typecheck MATRIX=true
